### ISSUE TITLE
Add Python and Java setup help

### ISSUE THREAD

**Issue by osoderholm** [Datateknologerna-vid-Abo-Akademi/gulis#13]
Add some simple guides to setting up Python 2.7 & 3.6 and Java. Does not need to be very in depth and external guides are welcome.

Python 2.7
- [x] Windows
- [x] Linux
- [x] macOS

Python 3.6
- [x] Windows
- [x] Linux
- [x] macOS

Java 8
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by LinAnt** [comment]
Python 2.7 is deprecated soon, I suggest it should be dropped, since alot of projects are already dropping python2 support. https://pythonclock.org/

**Comment by osoderholm** [comment]
I agree, however the first programming course will once again be done in Python 2.7 and therefore the setup for the old version must documented here. It is probably smart to add a note about the upcoming deprecation.
