### ISSUE TITLE
Create Linux page

### ISSUE THREAD

**Issue by osoderholm** [Datateknologerna-vid-Abo-Akademi/gulis#5]
The Linux page should contain the following:

- [x] Basic info
- [x] Basic commands
- [x] Useful links (at least to TUXEDO.md and old intro slides)

Maybe also add some exercises?

**Using tabs!**

Process management

Basic commands:

    Files/Directories:
        * ls - list files in directory
        * cd - change directory
        * rm - remove file/directory
        * cp - copy file/directory
        * mv - move file/directory
        * mkdir - create directory

    Text editors:
        * vim 
        * nano
        * gedit

    Networking:
        * ping - send a ping to an address
        * ssh (also in TUXEDO.md) - remotely connect to a computer
        * ifconfig - network interface configuration/info
        * iwconfig - like ifconfig but dedicated to wireless

* man
* top - terminal based task manager
* touch
* cat - read a file(s) and write to stdout
* echo
* grep
* pwd
* sudo - run program as another user
* whois
* whereis - search for location of file/program

Important to prioritise commands.

**Comment by LinAnt** [comment]
Commands:
du
stat
file

Also, | <> and tee

**Comment by LinAnt** [comment]
head
tail
less

**Comment by Faagerholm** [comment]
For now I suggest we close this issue, I think we should split this into basic commands and more advanced commands and add LinAnt's suggestions.
