### ISSUE TITLE
Come up with a name for the code club

### ISSUE THREAD

**Issue by osoderholm** [Datateknologerna-vid-Abo-Akademi/gulis#8]
Something smart and unique

**Comment by siikasmaa** [comment]
Code with DaTe

**Comment by Faagerholm** [comment]
Utskottet för dom mindre intellektuella

**Comment by Faagerholm** [comment]
Programmerings Utzkottet

**Comment by Faagerholm** [comment]
auxiliary club

**Comment by osoderholm** [comment]
Afterschool Coders

**Comment by Faagerholm** [comment]
Keyboard warriors / Tangentbords krigare

**Comment by LinAnt** [comment]
'/dev/utzkottet'

**Comment by osoderholm** [comment]
The final name was KodarKlubben. This club has been suspended for now.
